resources:
  containers:
    - container: rust-mkl
      image: rustmath/mkl:latest

jobs:
  - job: 'pkg_config'
    pool:
      vmImage: 'ubuntu-16.04'
    container: rust-mkl
    steps:
      - script: cargo test -v
        displayName: run test

  - job: Linux
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: cargo test -v
        displayName: run test

  - job: macOS
    pool:
      vmImage: 'macOS-10.14'
    steps:
      - script: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
        displayName: install rustup
      - script: cargo test -v
        displayName: run test

  - job: Windows
    pool:
      vmImage: 'windows-2019'
    steps:
      - script: |
          curl -sSf -o rustup-init.exe https://win.rustup.rs
          rustup-init.exe -y 2>&1
          set PATH=%PATH%;%USERPROFILE%\.cargo\bin
          echo '##vso[task.setvariable variable=PATH;]%PATH%;%USERPROFILE%\.cargo\bin'
        displayName: install rustup on Windows
      - script: cargo test -v 2>&1
        displayName: run test
